fix: dependency-analysis bug

diff --git a/apps/relayer/fhevm-relayer/.github/workflows/dependency_analysis.yml b/apps/relayer/fhevm-relayer/.github/workflows/dependency_analysis.yml
--- a/apps/relayer/fhevm-relayer/.github/workflows/dependency_analysis.yml
+++ b/apps/relayer/fhevm-relayer/.github/workflows/dependency_analysis.yml
@@ -32,12 +32,7 @@ jobs:
 
       - name: Check that Cargo.lock is the source of truth
         run: |
-          cargo update
-          
-          cargo update -w --locked
-          
-          # Check if the update created any changes
-          git diff --exit-code Cargo.lock || (echo "Error: Cargo.lock is out of sync. Please run 'cargo update' locally and commit changes" && exit 1)
+          cargo update -w --locked || (echo "Error: Cargo.lock is out of sync. Please run 'cargo update' locally and commit changes" && exit 1)
 
       - name: License whitelist
         run: cargo-deny deny check license --deny license-not-encountered
