Add Trivy summary to Github Job Summary (#221)
* chore: adds table summary and print it to github-summary

* chore: removes exit-code 1 and get total of vulns, miscfg and secrets

* chore: adds colored text in job summary

* chore: comments 'exit 1' to avoid enforcing zero-vulns

* chore: enables 'exit 1' to enforce zero-vulns in repo

* chore: fix typo

* chore: disables enforcement zer-vulns

diff --git a/.github/workflows/01-sca-trivy-repo.yaml b/.github/workflows/01-sca-trivy-repo.yaml
--- a/.github/workflows/01-sca-trivy-repo.yaml
+++ b/.github/workflows/01-sca-trivy-repo.yaml
@@ -70,46 +70,32 @@ jobs:
         if: success() || failure()
         run: |
             echo "=============== [ Installing Trivy and scan2html plugin ]"
-            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/cd01f230315a364b0eea35edb8db1c4c73c7019a/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.58.0
+            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/7f41822d4f916615c528caf5cbd640183d21a4f8/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.61.0
             trivy -v
             trivy plugin install github.com/fatihtokus/scan2html
 
-            REPORT_TITLE_REPO_VALUE="[ ${{ needs.prepare.outputs.GH_ORG_REPO_NAME }} | ${{ needs.prepare.outputs.GIT_HASH_SHORT }} | ${{ needs.prepare.outputs.DATE_BUILD }} ]"
-            REPORT_FILE_NAME="${{ needs.prepare.outputs.GH_ORG_REPO_NAME }}.${{ needs.prepare.outputs.GIT_HASH_SHORT }}.${{ needs.prepare.outputs.DATE_BUILD }}"
-            TARGET_CHILD_REPO_TO_SCAN="."
+            REPORT_TITLE="[ ${{ needs.prepare.outputs.GH_ORG_REPO_NAME }} | ${{ needs.prepare.outputs.GIT_HASH_SHORT }} | ${{ needs.prepare.outputs.DATE_BUILD }} ]"
+            REPORT_NAME="${{ needs.prepare.outputs.GH_ORG_REPO_NAME }}.${{ needs.prepare.outputs.GIT_HASH_SHORT }}.${{ needs.prepare.outputs.DATE_BUILD }}"
+            TARGET_REPO="."
 
             ## Set vars
-            echo "REPORT_FILE_NAME=$REPORT_FILE_NAME" >> $GITHUB_OUTPUT
+            echo "REPORT_NAME=$REPORT_NAME" >> $GITHUB_OUTPUT
 
-            ## Send report to stdout
-            trivy fs \
-            --scanners secret,vuln,misconfig \
-            --quiet \
-            ${TARGET_CHILD_REPO_TO_SCAN}/
-
-            ## Generates sarif report
-            trivy fs -f sarif \
-            --scanners vuln,misconfig \
-            --quiet \
-            ${TARGET_CHILD_REPO_TO_SCAN}/  \
-            -o trivy.${REPORT_FILE_NAME}.sarif
-
-            ## Generates json report
-            trivy fs -f json \
-            --scanners vuln,misconfig \
-            --quiet \
-            ${TARGET_CHILD_REPO_TO_SCAN}/  \
-            -o trivy.${REPORT_FILE_NAME}.json
+            ## Generates json table and summary reports
+            trivy -q fs -f json --scanners secret,vuln,misconfig ${TARGET_REPO} -o trivy.${REPORT_NAME}.json
+            trivy -q fs --scanners secret,vuln,misconfig ${TARGET_REPO} -o trivy.${REPORT_NAME}.txt --dependency-tree
+            trivy -q fs --scanners secret,vuln,misconfig ${TARGET_REPO} -o trivy.${REPORT_NAME}.summary.txt --table-mode summary 
 
             ## Transform json report to html report
-            trivy scan2html generate \
-            --scan2html-flags --with-epss \
-            --output trivy.${REPORT_FILE_NAME}.html \
-            --report-title "$REPORT_TITLE_REPO_VALUE" \
-            --from trivy.${REPORT_FILE_NAME}.json &> /dev/null
+            trivy scan2html generate --scan2html-flags --with-epss \
+            --output trivy.${REPORT_NAME}.html --report-title "$REPORT_TITLE" \
+            --from trivy.${REPORT_NAME}.json &> /dev/null
+
+            ## Transform json report to sarif
+            trivy convert -f sarif trivy.${REPORT_NAME}.json -o trivy.${REPORT_NAME}.sarif
 
             echo "=============== [ List of Trivy reports generated ]"
-            find . -type f -iregex ".*/trivy\..*\..+" | grep -E "json|sarif|html"
+            find . -type f -iregex ".*/trivy\..*\..+" | grep -E "json|sarif|html|txt"
 
             echo "=============== [ Import SARIF Trivy Report into GitHub Security Hub: ${{ github.event.inputs.import_sarif_into_github }}]"
 
@@ -117,17 +103,56 @@ jobs:
         uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882    # v4.4.3
         if: success() || failure()
         with:
-          name: trivy.reports.${{ steps.run_trivy.outputs.REPORT_FILE_NAME }}
+          name: trivy.reports.${{ steps.run_trivy.outputs.REPORT_NAME }}
           path: |
             trivy.*.html
             trivy.*.sarif
             trivy.*.json
+            trivy.*.txt
 
       # Works in public repos always and only with private repos in GH Enterprise + Advanced Security.
       # Set true if you have GH Enterprise + Advanced Security enabled for private repos.
-      - name: Load Trivy SARIF Report to GitHub Security Hub
+      - name: Load Trivy SARIF Report to GitHub Security
         uses: github/codeql-action/upload-sarif@ea9e4e37992a54ee68a9622e985e60c8e8f12d9f    # v3.27.4
         if: github.event.inputs.import_sarif_into_github == 'import-it'
         with:
-          sarif_file: trivy.${{ steps.run_trivy.outputs.REPORT_FILE_NAME }}.sarif
+          sarif_file: trivy.${{ steps.run_trivy.outputs.REPORT_NAME }}.sarif
           category: sca-trivy-repo
+
+      - name: Print Trivy table summary
+        if: success() || failure()
+        run: |
+            trivy_report_txt=trivy.${{ steps.run_trivy.outputs.REPORT_NAME }}.summary.txt
+            trivy_report_json=trivy.${{ steps.run_trivy.outputs.REPORT_NAME }}.json
+
+            ## Extract total of detected issues
+            TRIVY_ISSUES_VULNS=$(jq '[.Results[].Vulnerabilities[]?] | length' ${trivy_report_json})
+            TRIVY_ISSUES_MISCFG=$(jq '[.Results[].Misconfigurations[]?] | length' ${trivy_report_json})
+            TRIVY_ISSUES_SECRETS=$(jq '[.Results[].Secrets[]?] | length' ${trivy_report_json})
+
+            if [ "$TRIVY_ISSUES_VULNS" -eq 0 ] && [ "$TRIVY_ISSUES_MISCFG" -eq 0 ] && [ "$TRIVY_ISSUES_SECRETS" -eq 0 ]; then
+                echo ':white_check_mark: **Trivy** $${\color{green}NOT FOUND}$$ **issues in your Repo**' >> $GITHUB_STEP_SUMMARY
+                ENFORCE_ZERO_VULNS=NOT
+            else
+                echo ':x: **Trivy** $${\color{red}FOUND}$$ **issues in your Repo**' >> $GITHUB_STEP_SUMMARY
+                ENFORCE_ZERO_VULNS=YES
+            fi
+
+            if [[ -s "${trivy_report_txt}" ]]; then
+            {
+                echo "### Security Output"
+                echo "<details><summary>Click to expand</summary>"
+                echo ""
+                echo '```terraform'
+                cat "${trivy_report_txt}"
+                echo '```'
+                echo "</details>"
+            } >> "${GITHUB_STEP_SUMMARY}"
+            fi
+
+            echo ":information_source: Download Trivy Reports (Github artifact) for more information" >> $GITHUB_STEP_SUMMARY
+
+            # Enable next lines to exit 1 (vulns)
+            # if [ "$ENFORCE_ZERO_VULNS" = "YES" ]; then
+            #   exit 1
+            # fi
