feat(gateway-contracts): implement single keygen
* feat(gateway-contracts): implement single keygen

* test(gateway-contracts): fix KmsManagement tests and few contract logic

* fix(gateway-contracts): adjust Decryption event param names and fix mock tests/contracts

* chore(gateway-contracts): rollback to keygen method name

* feat(gateway-contracts): introduce keygen threshold and clean KmsManagement from deprecated vars

* refactor(gateway-contracts): rename KmsManagement contract to KMSManagement

* chore(gateway-contracts): update bindings and mocks

* chore(gateway-contracts): execute git mv for case-sensitiveness

* chore(gateway-contracts): execute git mv for case-sensitiveness

* fix(gateway-contracts): include missed keygen threshold parameter on upgrade

* refactor(gateway-contracts): rename task file for FHE keys gen

---------

Co-authored-by: Isaac Herrera <isaac.herrera@zama.ai>

diff --git a/.github/workflows/gateway-contracts-deployment-tests.yml b/.github/workflows/gateway-contracts-deployment-tests.yml
--- a/.github/workflows/gateway-contracts-deployment-tests.yml
+++ b/.github/workflows/gateway-contracts-deployment-tests.yml
@@ -95,6 +95,20 @@ jobs:
             echo "Host chain registration completed successfully with expected completion message"
           fi
 
+          ## Check key generation triggering
+          timeout 300s bash -c 'while docker ps --filter "name=trigger-keygen" --format "{{.Status}}" | grep -q "Up"; do sleep 5; done'
+          docker compose logs trigger-keygen > keygen_logs.txt
+          EXIT_CODE_KEYGEN=$(docker inspect --format='{{.State.ExitCode}}' trigger-keygen)
+          if [ "$EXIT_CODE_KEYGEN" -ne 0 ]; then
+            echo "Key generation triggering failed with exit code $EXIT_CODE_KEYGEN"
+            exit 1
+          elif ! grep -q "Keygen triggering done!" keygen_logs.txt; then
+            echo "Key generation triggering did not complete successfully - 'Keygen triggering done!' message not found in logs"
+            exit 1
+          else
+            echo "Key generation triggering completed successfully with expected completion message"
+          fi
+
       - name: Clean up
         working-directory: gateway-contracts
         if: always()
